# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6edbd9fe06fcbf0afa0dcd91adf06be652ba6ac9b3d72a0c24418e5790056d7ecc42f4945fe2a4a15e01b5aef3311b914f9d3d37bf08f4288b11554ee596bf32

test:
  secret_key_base: 00714738bc5ca07517adc2c90913093f7e0c0c74134c358a9f58fd8589f36ffa6bc60b7a9645829b5ab1abad64306d426717e55dae1b99ae99b126ebaf290098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
